### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by BolieRide** [Taurahh/Kobold-King-Maps-Remade-by-Taurah#2]
I am using this for Savage Pathfinder, but it does not show up in v11.  Is there something that I can do to get it to work in v11?
Thanks!

**Comment by ennerre25** [comment]
This is not related to v11, the module is configured to be detected as PF2E only. You need to download it to your PC, extract it and open the module.json file with a text editor and delete the references to the PF2E system. Then compress it again into a zip file and install it directly from your PC rather than using the one provided in the module browser. 
If you use The Forge, use the Summon Import Wizard to install and remember to untick the option to install from the Baazar if available.
Also, when you use the maps ingame don't forget to change the measurements from 5ft. to 1in.
